version: "3.8"
services:
  mongo:
    image: mongo:latest
    command: mongod --quiet
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=data
      - MONGO_DB_USERNAME=user
      - MONGO_DB_PASSWORD=user
    networks:
      main-network:
    
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: no-ctf
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=db
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=admin
      - SPRING_DATA_MONGODB_DATABASE=db
    networks:
      main-network:

networks:
  main-network: